# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2024 Ferdinand Thiessen <opensource@fthiessen.de>
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "nextcloud-vite-config"
SPDX-PackageSupplier = "Nextcloud GmbH and Nextcloud contributors"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud-libraries/nextcloud-vite-config"

[[annotations]]
path = ["package-lock.json", "package.json", "tsconfig.json", "**/package.json", "**/package-lock.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"
